name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  flutter_riverpod: 2.3.6
  go_router: 7.1.1
  equatable: 2.0.5
  firebase_core: 2.13.0
  firebase_auth: 4.6.1
  firebase_ui_auth: 1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
