name: flutter_starter
description: "Learn to write integration test for your app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: any
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  collection: ^1.19.0
  get_it: ^8.0.3
  provider: ^6.1.2
  dio: ^5.7.0
  jwt_decode: ^0.3.1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  freezed: ^2.5.8
  json_serializable: ^6.9.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
